### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by AverageMarcus** [jsoxford/jsoxford.github.com#107]
@benfoxall  has expressed a desire for a new JS Oxford logo.

Opening this issue for discussion / examples.

@peterjwest - [Below](https://github.com/jsoxford/jsoxford.github.com/issues/107#issuecomment-93684403)

> I think the rough brief is:
> - We like the JS community logo, we (probably) want to keep that recognisable
> - It should clearly say 'JS Oxford', our current logo just has Oxford tacked on, it doesn't look like part of the logo
> - We want something cool and exciting - vibrant, embracive a bit messy, PARTY, that kind of thing

**Comment by hturan** [comment]
Just to get the ball rolling, I spent an hour or so sketching around in Sketch:

![screen shot 2015-04-15 at 22 40 22](https://cloud.githubusercontent.com/assets/65447/7169780/79ab40ce-e3c0-11e4-89e4-038d47055f89.png)

I guess one of the key questions is how closely we want to stick to the [JS community logo](https://github.com/voodootikigod/logo.js). It's not particularly descriptive and there are only so many ways you can fit 'Oxford' into a square :smile: Skylines and such can be redrawn properly, if we decide to go down that route.

Also, I'm new here :wave: Sorry if I'm treading on anyone's toes or messing up process! Happy to clean up the Sketch file and post it here if people want to play around with it.

**Comment by AverageMarcus** [comment]
Hi @hturan welcome to the community! :wave: 

These look awesome! Don't feel like you're treading on anyone's toes, we're happy for everyone to contribute! :+1:

My faves:
![image](https://cloud.githubusercontent.com/assets/3384072/7174087/d2d10c40-e3f9-11e4-8813-e6e631b30b0f.png)
![image](https://cloud.githubusercontent.com/assets/3384072/7174088/da184bd0-e3f9-11e4-8b84-a180ad8706bd.png)

**Comment by spikeheap** [comment]
Hi @hturan, I'll second @AverageMarcus's welcome, and thanks for getting involved :clap:.

I like the simple switch to Oxford Blue (is that a trademarked colour?):
![](https://cloud.githubusercontent.com/assets/3384072/7174088/da184bd0-e3f9-11e4-8b84-a180ad8706bd.png)

I've become quite attached to JS-yellow, and think it helps to identify us as a JS meetup group (e.g. on http://summerofhacks.io, so I think my favourite is one of the skylines:
![](https://cloud.githubusercontent.com/assets/3384072/7174087/d2d10c40-e3f9-11e4-8813-e6e631b30b0f.png).

If we use a skyline, I wonder how we can make it _so_ distinctive that it's obviously Oxford, without having to use 'Oxford'. We'll be using the logo standalone (hence adding 'Oxford' to the original JS logo)

I do like the 'JS; OX;' approach, particularly because it keeps the JS yellow, is minimal, but gets a lot across. I wonder if it should we could stylise something like `js(ox);` in a similar way.

We also need to think about how the logo will sit on backgrounds we can't control.

It would be great to get the Sketch file into GH so everyone can play, we should probably have a `logo` repo for that: https://github.com/jsoxford/logo. 

This is awesome @hturan, good effort!

**Comment by LuRsT** [comment]
I like it :+1:

**Comment by peterjwest** [comment]
I have an idea for a logo, will have a go tonight.

**Comment by omgmog** [comment]
![](http://i.imgur.com/cDyfVdY.jpg)

![](http://i.imgur.com/ejV2mtm.png)

**Comment by LuRsT** [comment]
It's actually the best!

**Comment by jimmymorrisuk** [comment]
If I wasn't going away I'd produce something. When do you need it for?
What's the brief?

**Comment by peterjwest** [comment]
I think the rough brief is:
- We like the JS community logo, we (probably) want to keep that recognisable
- It should clearly say 'JS Oxford', our current logo just has Oxford tacked on, it doesn't look like part of the logo
- We want something cool and exciting - vibrant, embracive a bit messy, PARTY, that kind of thing

**Comment by spikeheap** [comment]
@jimmymorrisuk good point! @benfoxall and @peterjwest probably have some things to add/change here, but:

Target audience: We want to increase diversity in the Oxford technology scene, so our target audience includes both men and women, and includes front-end developers, hardware hackers, full-stack developers, and people new to JS and development.

Uses: The logo will be used in a number of places:

* Our website, GitHub Org and Twitter feed
* Other websites which link to us
* Slides and event materials

The logo needs to convey that we're a JS organisation, and that we're in Oxford. The 'Oxford' thing is important because that's where the meetups and events take place, and is (probably) more important than the 'JS' bit.

Because the logo will be used on things like the Twitter feed, it needs to be recognisable at small sizes.

Stylistic preferences: we're open to pretty much anything, but there are a few things we like about our existing logo (other than that we didn't need to design it!):

* Clean and minimal
* Bold

We're less keen on 'Oxford' being tacked on underneath the core JS square.

Colors: We used the JS-yellow/black combo for convenience, but a few of us have become a little attached to it. The Oxford-blue samples above are interesting too though, and seem to work well with the yellow (though I am colour-blind...).

**Comment by spikeheap** [comment]
snap @peterjwest, 'PARTY' is one of our core values, right?

**Comment by AverageMarcus** [comment]
@spikeheap  do you want to update the first comment to reflect your comment, and maybe @benfoxall will also add anything he feels relevant?

**Comment by danielthepope** [comment]
...and in true danielthepope-style-rushed-fashion: I really like @hturan's skyline idea, AND the Oxford blue, so how about something like this?
![jsoxford-blueskyline](https://cloud.githubusercontent.com/assets/5173183/7177839/d29154f6-e421-11e4-886a-38837f228d0e.png)

**Comment by jimmymorrisuk** [comment]
Just my opinion and I'm not knocking the skill but I feel like to much association of the place in a logo isn't a great move. It's kind of a cliche, arguably a bad one. Firstly you're relying on people to know it's Oxford's skyline in the first place. The logo should really be reusable in multiple situations, the fact it's in Oxford is a parameter of it as secondary thought after you've understood what the logo is about. 

Open minded though.

**Comment by LuRsT** [comment]
Is it really secondary that JS Oxford is in Oxford? In my opinion it's quite primary, you can't have JS Oxford elsewhere. As for the skyline not being explicit, I agree, but I think it's a nice sort of "easter egg" having a skyline that some people will immediately know that it's oxford while others will have to ask, which creates buzz as a bonus

**Comment by hturan** [comment]
Thanks for all the feedback, great to see so much discussion :+1:

Following on from the comments by @spikeheap, @peterjwest and @jimmymorrisuk above, I'm leaning more towards something based on:

![screen shot 2015-04-16 at 10 39 26](https://cloud.githubusercontent.com/assets/65447/7179091/5406951e-e42c-11e4-94f4-801400154e5b.png)

It's clean, fun, and it says 'JS Oxford'! It's not very JavaScript-y or Oxford-y, but it's pretty clear regardless. Would be quite easy to extend for events, too.

Also, sorry for not having uploaded the source file, it's on my laptop at home. I'll upload it here when I get back from work (version control? what's that?) :sweat_smile:

**Comment by peterjwest** [comment]
I'm against the skyline personally, it's been done to death and only helps if you know Oxford's skyline.

**Comment by hturan** [comment]
Okay! Here are the `.sketch` and `.svg` files for the sketches above. Excuse the mess.

https://www.dropbox.com/s/fj1lt0vooi89gtq/JS%20Oxford%20Logo%20Sketches%20%28Export%29.sketch?dl=1
https://www.dropbox.com/s/sfeg0jktlerj18c/JS%20Oxford%20Logo%20Sketches%20%28Export%29.svg?dl=1

I've converted the type to paths and the ASCII to a bitmap, so it should render fine. Font is `Neutra Text Bold`, as used in the original JS Logo. Also, the skylines (apart from the Rad Cam) are bitmaps, but will be easy enough to draw out as vectors if we want to go that route.

**Comment by spikeheap** [comment]
Lots to think about! I think @jimmymorrisuk and @LuRsT both make good points. My 2 cents:

* I think we can satisfy the 'recognisably JS' __either__ by using the JS yellow __or__ the box/JS pattern. If we we aim for both, we don't have many options.
* I don't mind the skyline, but I agree it's quite overdone, and I don't recognise it even though I live here ;). 
* I think we're getting boxed in around the above, which will make it difficult to get creative suggestions. __Please add any ideas or outlines here, a) because it's awesome to see, and b) we don't know that we don't like what we haven't seen__.

Let's collect ideas and thoughts for a couple of weeks. After that we'll do a critical round where we can all say what we don't like and why, and then we can run a straw-poll to see what the consensus is.

**Comment by hturan** [comment]
> I think we're getting boxed in around the above, which will make it difficult to get creative suggestions.

Agreed :100:, looking forward to seeing this evolve!

**Comment by spikeheap** [comment]
Also, I really liked @hturan's idea of stylising the information in javascript (I'm a massive geek and have a set of [these](http://varianto25.com/). I have the graphic design skills of a freshly picked apple, so I've resorted to pen an post-it for a suggestion for inspiration:
![img_0064](https://cloud.githubusercontent.com/assets/464482/7192008/c5d10370-e489-11e4-9f1a-f5ddf9146015.JPG)

Not that, but something like that might be nice. Or not.

**Comment by benfoxall** [comment]
My favourite so far has been the blue square, though just realised it's similar to [EdinburghJS](https://twitter.com/edinburghjs).  I'd like to have something along those lines that is simple and flexible, we should be able to make things that look "JSOxfordish" - not just plonk our logo on top of it.

Taking edinburghJS - their [site](http://edinburghjs.org/) has an ascii version of the logo - which is awesome.  If we choose something too complex like skylines - then it would make it harder to do this kind of stuff.

As I said ages ago in the pub, I'm keen to see something recognisable, awesome and bold.

**Comment by rjmunro** [comment]
I'd either go with skylines (I like @omgmog's yellow on blue, I'd also try blue on yellow), or just add Oxford to the community logo something like this:
![jsox](https://cloud.githubusercontent.com/assets/108641/7387846/893feb14-ee58-11e4-917e-266036e8549c.png)

**Comment by peterjwest** [comment]
I was thinking of something completely different...
![logo](https://cloud.githubusercontent.com/assets/246023/7398391/a0674424-eea6-11e4-8226-cbca6ea98b22.png)

**Comment by AverageMarcus** [comment]
And we have a winner!

**Comment by omgmog** [comment]
> I was thinking of something completely different...

Going to need that to be an ox, not a horse!

**Comment by peterjwest** [comment]
It's the standard horse.

**Comment by peterjwest** [comment]
An Ox would make a lot more sense, but I feel that making too much sense would not be in the spirit of JSOxford.

**Comment by tomlane** [comment]
:+1: :smile:

**Comment by sarahplant** [comment]
![a0674424-eea6-11e4-8226-cbca6ea98b22-1](https://cloud.githubusercontent.com/assets/7736022/7410172/545cd8ea-ef24-11e4-98dc-56282958bfca.png)

**Comment by peterjwest** [comment]
![logo](https://cloud.githubusercontent.com/assets/246023/7477484/0c16092c-f34c-11e4-826b-5666d9dffed8.png)

Tweaked blue to improve contrast around "Oxford".
I've also sent the illustrator file to @benfoxall as he wants to change stuff.

**Comment by AverageMarcus** [comment]
:+1:
![](https://files.gitter.im/jsoxford/jsoxford.github.com/HDE5/blob)
![](https://files.gitter.im/jsoxford/jsoxford.github.com/WCw2/blob)

**Comment by AverageMarcus** [comment]
So I'm in favour of...
![image](https://cloud.githubusercontent.com/assets/3384072/8761646/76fbc8da-2d53-11e5-9c9f-551263c158b9.png)

When done as an SVG we have the ability to play around with it and add additional stuff, such as the standard horse, based on the event/usage.

Example: http://output.jsbin.com/jeyeqokuxa (with animation)

**Comment by tomlane** [comment]
That would make a pretty cool splash screen for the stream or a background slide along with the text "We'll be starting the event shortly" or something. 

Either way, it's super cool! :+1:

**Comment by AverageMarcus** [comment]
Take a look at http://jsoxford.com/welcome.html Similar idea

**Comment by omgmog** [comment]
![](https://media2.giphy.com/media/12Zl61Sx4JoB2w/giphy.gif)

Was this resolved? I guess we're sort of going full _standard horse_ these days... I mean, we've got a flag of it now. Will close this discussion just to tidy things up :100:
