### ISSUE TITLE
Replace web fonts with SVGs

### ISSUE THREAD

**Issue by spikeheap** [jsoxford/jsoxford.github.com#124]
We should replace the couple of FontAwesome icons we use for SVGs, because it's better for accessibility and general happiness (and because @ninjanails told us to).

There's only a couple of instances on the main page so it should be straightfoward: 

<img width="311" alt="jsoxford" src="https://cloud.githubusercontent.com/assets/464482/8718105/3adebd96-2b99-11e5-9b9a-9be4e88378fb.png">

**Comment by AverageMarcus** [comment]
@benfoxall is a whizz with SVGs right?

If we need SVG icons: https://thenounproject.com/

**Comment by omgmog** [comment]
They could be replaced with svg background images on the same <i> elements that are already there. Should even be able to use the same font-awesome.svg that we've got.

**Comment by towc** [comment]
or just make sure to use the attributes that specify that those are icons like "aria-*"? This way tools like screen readers and font replacers can distinguish them and treat them differently, as they should. No need to demote font-awesome, you just need make sure that those tools are updated to the standards, instead of having to change the standards for them, hence breaking other sites like github for who uses them

**Comment by AverageMarcus** [comment]
@towc Do font replacers take note of aria attributes? (My gut reaction says no)

**Comment by towc** [comment]
@AverageMarcus many don't, but it's as if we're still in the era of IE7 for those tools. We need to make sure that those tools also change, instead of needing us to continuously make pretty time/performance-taking fallbacks and such. That's just my opinion anyway, but I think it's pretty valid: we don't want to support IE7 for the rest of our lives, right? Changes need to happen, and thankfully the majority of people jumped over to Chrome, FF and similar. Those tools deserve attention aswell, as ninjanails rightfully said, but we should also work on making them better instead of downgrading sites for them

**Comment by AverageMarcus** [comment]
I totally agree that those tools need to catch up but I don't think i consider moving to SVGs as "downgrading".

**Comment by spikeheap** [comment]
@towc I completely agree about the tools needing to improve, but some of them are built into the OS, so the user might not be able to upgrade it easily. Either way, I think this is a trivial change for us (we only have 3 font icons on our homepage) and I agree with @ninjanails fundamental point that fonts aren't really appropriate for images, because they're fonts. SVGs are more of a side-step than a downgrade too.

**Comment by omgmog** [comment]
So a couple of points:

1. You can use the same FA icons, just use [Icomoon](http://icomoon.io/app) to export each one that's needed as an individual SVG
2. Can use grunt/gulp/etc. to make a SVG sprite, and then inline that in the HTML somewhere, and refer to each icon individually through `<img>` or CSS `background-image`.
3. The elements can use `aria-hidden` to avoid being read by screen readers.

More on the process:

https://css-tricks.com/svg-sprites-use-better-icon-fonts/
http://24ways.org/2014/an-overview-of-svg-sprite-creation-techniques/

A bit more on "hidden" content for screen readers, http://www.html5accessibility.com/tests/hidden2013.html
