### ISSUE TITLE
SummerJS retro

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#128]
Yesterday was fairly great - any ideas of things we can carry forward & improve.

Chuck in any things in the comments and I'll bring it up to the main list.

We'll close this issue after we've totally owned the next meetup.

## Stuff

* emailing out details and running order to speakers worked well (partly for them, mostly for us)
* my intros kind of sucked
* we're almost there with live streaming
* tidying up was a bit challenging (due to the late finish)
* it was nice that so many people came to the bar
* we could do with a funky welcome image we can have up with wifi details etc.

## Actions [owner]

- [ ] speaker info template [@benfoxall]
- [ ] get back to shared intros/chat
- [x] set up jsoxford youtube channel [@AverageMarcus]
- [ ] make firmer plans for after-drinks
- [x] event slides (wifi, logo & pictures of Max and Marcus) [~~@benfoxall~~@AverageMarcus]
- [ ] give a "talks start at" time

**Comment by AverageMarcus** [comment]
Hold off on questions until social time worked well too.

**Comment by omgmog** [comment]
I'm not sure about leaving questions until the end. If the event runs until late and speakers have to get trains/etc, people won't get to ask them questions.

Which I guess goes on to some other points:

- perhaps try not to finish too late
- get the speakers on a separate wifi to everybody else, so that the wifi works for demos :bangbang:
- if we're going to have sponsored pitches at the start, perhaps more guidance for the pitchers might be useful.

Any chance of trying more central venues also? I get that it's super cool and convenient being at WO, but back to my previous point about having to get trains, it's a pain to get across town! The blue room at the St Aldates Tavern was cool, what are their rates like for venue hire?

**Comment by peterjwest** [comment]
I think sponsor pitches should probably have a time limit, it was a little long.

Also think we should do questions if we have time (yesterday we didn't, it was a good call).

We're looking at the Old Fire Station as a venue.

**Comment by omgmog** [comment]
OFS would be great! :+1:

**Comment by AverageMarcus** [comment]
We could do with a funky welcome image we can have up with wifi details etc.

**Comment by spikeheap** [comment]
How about @omgmog and @AverageMarcus wearing cardboards:
- [x] Funky
- [ ] Welcoming

**Comment by peterjwest** [comment]
+1

**Comment by benfoxall** [comment]
I think question/comment time is really good to get in if possible.  Don't really want people to come along and just listen to talks - want them to be bringing something along too.

> perhaps try not to finish too late

How about we start earlier?  Would 7pm be too early?  Talks start at 7.15pm.

> if we're going to have sponsored pitches at the start, perhaps more guidance for the pitchers might be useful.

Yup, I felt like we missed out a tiny bit on that pitch - they had some really interesting things (I'd love to know more about their asset graph tools)

**Comment by AverageMarcus** [comment]
One thing i think worth including with the email to speakers is info about the projector. Resolution, connectors etc.

**Comment by omgmog** [comment]
His email did have that info, it's just that OS X defaults to "clone" rather than dual screen, and so speakers wanting to do it that way have to dick around with window locations.

Might be solvable if each speaker tries the connection before JSOxford starts

**Comment by AverageMarcus** [comment]
Wow! @benfoxall really was organised!
