### ISSUE TITLE
Browser Ferraris (take 2) Retro

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#218]
We had an event last night - [Browser Ferraris, take 2](http://www.meetup.com/JSOxford/events/230524761/)

Any observations/comments would be appreciated. Especially with some kind of action that we can take forward.  
---

Add a comment to this issue, and we'll update the main body to gather everything together

**Comment by benfoxall** [comment]
* @spikeheap touched on it at the end - but it would be good to highlight how intimidating coming to a meetup can be, and to make sure that new people feel welcome. Perhaps we could start with this next time?
* It sucked that St Aldates was so busy.  Perhaps we could pre-book somewhere nearby?

**Comment by omgmog** [comment]
Controversial point, but perhaps there wasn't enough _JavaScript_ in the talk selection? (as awesome as they were besides that!)

**Comment by peterjwest** [comment]
Did you find another pub? I think we just need a go-to backup.
A touch more coding would have been good.

**Comment by AverageMarcus** [comment]
As we usually have two main talks we could try and aim for one JavaScript-y code goodness and one that is more general web/tech related? Give a nice balance.

**Comment by spikeheap** [comment]
#### What went well?
- I had a good time. That's the important thing, right? 
- The talks were great, and from local speakers which was amazing.
- There was just the right number of drinks.
- Diversity. We had more first-time attendees, and more female attendees, which is hopefully a sign that our events are becoming more accessible. Mentioning the CoC and it's purpose felt really positive (though I'm pretty biased).
- Having breaks between the talks worked well from an organiser point of view (I'd be keen to find out if it was good or felt forced for attendees), giving us time to set up slides/mics/etc.
- Show and Tell. That blew my mind.

#### What could improve?
- Signage. We needed to have someone out front directing people in. Anyone early or late might not be able to find us. A couple of pop-up bright yellow standing posters with laser horses would solve that.
- Diversity. Because there's still loads we can do to improve our events and make them more accessible to underrepresented groups.

**Comment by AverageMarcus** [comment]
The breaks between the talks was really good. I prefer having the time to let things sink in, go grab a drink and run to the toilet.

I think some go-to slides/images with URLs and stuff on would be useful. Stuff that can be re-used every meetup with the link to slack and the CoC etc.

Also, as I was walking home last night I got a notification from Chrome to tell me that beacon support has now arrived in Chrome on android. It might be nice to have a beacon with the CoC URL on.

**Comment by danielthepope** [comment]
Not much else to add here, but I'm going to anyway. I really enjoyed the evening - the breaks were useful both to help set up the next talks and for a little bit of extra socialising. I really like the format of the show and tell sessions as well. Totally agree with Max and Marcus too :)

**Comment by omgmog** [comment]
For the sake of speakers, what resolution is the new projector at the Story Museum?

**Comment by AverageMarcus** [comment]
@omgmog suggestion should be included in #217

**Comment by peterjwest** [comment]
I think it supports any two primes
