### ISSUE TITLE
Talk suggestions

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#54]
If there's anything in particular that you'd like to hear about at JSOxford - chuck it in here.

**Comment by benfoxall** [comment]
* Arrow-ized FRP (#43)
* hood.ie - (there are [talk templates](http://hood.ie/contribute/#talks) on the hood.ie site)
* service workers 
* webAudio
* webGL
* ~~react~~ (this great to have last year)

**Comment by benfoxall** [comment]
* Web Components!

**Comment by richdouglasevans** [comment]
I use [Gulp](http://gulpjs.com/) at work. (Tho' it was [Grunt](http://gruntjs.com/) before that.) I'm noodling about stripping it all back to [plain old NPM scripts.](https://docs.npmjs.com/misc/scripts) Mainly because I'm too damn lazy to teach my colleagues about Grunt/Gulp -- their desire to teach themselves about Grunt/Gulp/Gradle/Goo is low and I can understand that -- and have no desire to be The Build Guy.

Have we had a talk about (JS) build tools *du jour?*

> Arrow-ized FRP (#43)

I rescind my suggestion for this as a topic. It still interests me, but on the stack of All The Possible Things One Could Talk About, it's low down.

**Comment by AverageMarcus** [comment]
I'd quite like someone to give a talk on structuring JavaScript. Things like module patterns and file/directory structure.

**Comment by richdouglasevans** [comment]
Ooh! Unless it's been done already/done to death, I'd like to hear a talk about Teh ES6 Hawtness. Alternatively, I could present a talk about ES6.

**Comment by AverageMarcus** [comment]
* Writing testable JavaScript
* JavaScript superset languages (TypeScript, CoffeeScript, etc.)
* Desktop apps (node-webkit?)

**Comment by richdouglasevans** [comment]
* Writing testable JavaScript

:+1:

* JavaScript superset languages (TypeScript, CoffeeScript, etc.)

+1/2. I've got Clojure(Script) on my "Learn A Language" plate at the moment so while potentially adding more is always interesting I only have so many hours in the day. I totally support this topic though, I'm not raining on it, just sharing where I am. I investigated CS a few years ago, but couldn't interest the folks on the gig I was at at the time to invest in it, and with ES6 on the horizon I dunno that i want to revisit CS personally.

* Desktop apps (node-webkit?)

:+1: I know nothing about this topic, so getting an introduction to it would be good.

**Comment by spikeheap** [comment]
* JavaScript superset languages (TypeScript, CoffeeScript, etc.)
It might be worth talking about ES6 as part of this, even though it's sort of different: http://robots.thoughtbot.com/replace-coffeescript-with-es6

**Comment by AverageMarcus** [comment]
I'd personally be interested in a talk on TypeScript. I tried to use it some months ago before it was out of beta but didn't make much progress. Coffee script doesn't really interest me as a language but I mentioned it as I'd quite like a more general talk about the idea and motivation behind superset languages and how they work behind the scenes.

@spikeheap I wouldn't mind seeing a talk on ES6 alone.

**Comment by AverageMarcus** [comment]
We should have totally put together this list and asked if anyone was up for giving a talk on one of the topics.

**Comment by richdouglasevans** [comment]
Totes.

Marcus, would you mind putting together just such a list to present at the next JSOxford Meetup so that we can solicit talks from the gathered cognoscenti?

:smile_cat:

Or, you know, I could do it and stop being lazy :smile: :blush:

Actually, I'm gonna do it. On the sole slide, the ideas are gonna pour out of [Ben's Mind Palace.](http://www.bensmindpalace.co.uk/)

**Comment by AverageMarcus** [comment]
I was thinking something along the lines of a flip chart where people could add their name.

**Comment by richdouglasevans** [comment]
Yeah! A flipchart... with Ben's Mind Palace picture at the bottom and a stack of index cards shaped like clouds that folks can scribble talks onto and Blu-Tack into place above Ben's bonce like thought bubbles.

I wonder if folk would playfully abuse it. Also, I really don't know Ben well enough to be this forward.

**Comment by AverageMarcus** [comment]
Do it! It sounds like a perfect way to get people to talk about talks :stuck_out_tongue_winking_eye:

**Comment by peterjwest** [comment]
I'd be happy to do a talk on clojurescript or testing javascript.
Also, +1 ES6

**Comment by benfoxall** [comment]
[nw.js](http://nwjs.io/) looks interesting (I'm watching a live demo of it at smashing conf at the moment).

**Comment by peterjwest** [comment]
You'd kind of expect their logo to point North West...

**Comment by AverageMarcus** [comment]
@peterjwest  https://www.reddit.com/r/javascript/comments/2sfm0w/nodewebkit_is_now_nwjs/cnp7k63 :wink:

**Comment by peterjwest** [comment]
Even though I'm an idiot, it's still not a true NW more like WNW

**Comment by AverageMarcus** [comment]
If we can get someone to come give a talk about "Reactive functional javascript" and explain it in child words I'd love it!

**Comment by richdouglasevans** [comment]
Following on from Pete's "Testing With JavaScript" talk from May's Meetup, how about a _short_ talk on [Wallaby.js?](http://wallabyjs.com/)

I am _really_ digging this continuous testing tool. It is niche because it's just for the more heavyweight IDEs at the moment (JetBrains, VS.) at the time of writing. If it's just a short talk it might be palatable to those who don't have an investment in those IDEs, and it's Javascript testing-focused so it has that generally interesting aspect.

**Comment by tomlane** [comment]
How about something on the lighter side?

https://www.destroyallsoftware.com/talks/wat
http://www.hanselman.com/blog/DeveloperStandUpComedyCoding4Fun.aspx

**Comment by peterjwest** [comment]
I would LOVE to do a comedy coding talk, getting good material is tough though.

**Comment by richdouglasevans** [comment]
Stuff that's been interesting me of late may be of interest to others.

* Publishing Your First [Node](https://nodejs.org/) Module To [NPM](https://www.npmjs.com/) : _Earn $$$!!!1!_
* [Electron](http://electron.atom.io/) :: _cross platform desktop apps with web technologies_
* [Transducers](https://www.youtube.com/watch?v=6mTbuzafcII) In Javascript
* Microservices With [AWS Lambda](https://aws.amazon.com/lambda/)
* How To Join The Javascript Adventure Club

I could talk about any of 'em except that last one. _::wistful sigh::_ It'd be awesome if someone could do that last talk. I've never wanted anything so bad since Crimbo 1984 and _that_ Skeletor action figure.

![Not She-Ra!](http://4.bp.blogspot.com/_BXiLAmoEpMI/SNfYVOaG7tI/AAAAAAAABxo/scowvZQz9c4/s320/Skelly_Panthro+004.jpg)

**Comment by danielthepope** [comment]
I'd be keen to learn about Electron in particular. I tried it once, got stuck, resorted to Java Swing, cried then gave up.

-----Original Message-----

**Comment by richdouglasevans** [comment]
Way back in January Ben [suggested](#issuecomment-71167786) the topic of [Service Workers.](http://www.html5rocks.com/en/tutorials/service-worker/introduction/)

When Ben was giving his talk last night and asked _"Who knows about Service Workers?"_ more hands stayed down than went up.

So here's a bump for a talk on Service Workers. Ben's already whetted the appetite.

> I'd be keen to learn about Electron in particular.

Maybe the folk at the [Docker Hack Day](http://www.meetup.com/docker-oxford/events/224783546/) will expose an API that could be neatly surfaced via Electron with some neat desktop integration. I'll mention it and see if anything shakes out.

**Comment by tomlane** [comment]
:+1: for Service Workers. Even if its something like "I had a go and this is what I learned/found out/got bitten by"

**Comment by peterjwest** [comment]
I heard @spikeheap knows a lot about service workers, he basically got @benfoxall's demo working

**Comment by AverageMarcus** [comment]
Doesn't he do that for all @benfoxall's demos?

**Comment by AverageMarcus** [comment]
Picking this issue back up...

I'd love to see a talk on AMP.

**Comment by omgmog** [comment]
I could probably talk about adding service workers to my blog, and the gotchas with debugging them. 

Though I'm still at a loss for the real benefit (for the average user), or best practices, what to cache, etc.

**Comment by AverageMarcus** [comment]
Another one: 

* Procedurally built environments / levels / things. (game dev or otherwise)

**Comment by benfoxall** [comment]
I've started a github project for tracking talks:

https://github.com/jsoxford/jsoxford.github.com/projects/1

I _think_ it's going to work a bit better for suggesting talks, finding speakers and assigning them to events. So I'm going to close this issue (hope that's cool).

I've copied across a few of the topics from here,  though feel free to add some ideas into the "topics wanted" column
